CREATE TABLE IF NOT EXISTS [Album](
    [Id] GUID PRIMARY KEY ASC ON CONFLICT ABORT NOT NULL ON CONFLICT ABORT UNIQUE ON CONFLICT ABORT, 
    [Name] NVARCHAR NOT NULL ON CONFLICT ABORT, 
    [CollectionId] GUID NOT NULL ON CONFLICT ABORT REFERENCES Collection([Id]) ON DELETE CASCADE ON UPDATE NO ACTION, 
    [ArtistIds] NVARCHAR, 
    UNIQUE([CollectionId] ASC, [ArtistIds] ASC, [Name] ASC) ON CONFLICT ABORT);

CREATE TABLE IF NOT EXISTS [Artist](
    [Id] GUID PRIMARY KEY ASC ON CONFLICT ABORT NOT NULL ON CONFLICT ABORT UNIQUE ON CONFLICT ABORT, 
    [Name] NVARCHAR NOT NULL ON CONFLICT ABORT, 
    [CollectionId] GUID NOT NULL ON CONFLICT ABORT REFERENCES Collection([Id]) ON DELETE CASCADE ON UPDATE NO ACTION, 
    UNIQUE([CollectionId] ASC, [Name] ASC) ON CONFLICT ABORT);

CREATE TABLE IF NOT EXISTS [ArtistToAlbum](
    [ArtistId] GUID NOT NULL ON CONFLICT ABORT REFERENCES Artist([Id]) ON DELETE CASCADE ON UPDATE NO ACTION, 
    [AlbumId] GUID NOT NULL ON CONFLICT ABORT REFERENCES Album([Id]) ON DELETE CASCADE ON UPDATE NO ACTION, 
    UNIQUE([ArtistId] ASC, [AlbumId] ASC) ON CONFLICT ABORT);

CREATE TABLE IF NOT EXISTS [ArtistToTrack](
    [ArtistId] GUID NOT NULL ON CONFLICT ABORT REFERENCES Artist([Id]) ON DELETE CASCADE ON UPDATE NO ACTION, 
    [TrackId] GUID NOT NULL ON CONFLICT ABORT REFERENCES Track([Id]) ON DELETE CASCADE ON UPDATE NO ACTION, 
    UNIQUE([ArtistId] ASC, [TrackId] ASC) ON CONFLICT ABORT);

CREATE TABLE IF NOT EXISTS [Chat](
    [UserId] GUID NOT NULL ON CONFLICT ABORT REFERENCES User([Id]) ON DELETE CASCADE ON UPDATE NO ACTION, 
    [Timestamp] DATETIME NOT NULL ON CONFLICT ABORT, 
    [Message] NVARCHAR NOT NULL ON CONFLICT ABORT);

CREATE TABLE IF NOT EXISTS [Collection](
    [Id] GUID PRIMARY KEY ASC ON CONFLICT ABORT NOT NULL ON CONFLICT ABORT UNIQUE ON CONFLICT ABORT, 
    [Name] NVARCHAR NOT NULL ON CONFLICT ABORT UNIQUE ON CONFLICT ABORT, 
    [Filter] NVARCHAR NOT NULL ON CONFLICT ABORT, 
    [Path] NVARCHAR NOT NULL ON CONFLICT ABORT, 
    UNIQUE([Name] COLLATE [NOCASE] ASC) ON CONFLICT ABORT);

CREATE TABLE IF NOT EXISTS [ComposerToTrack](
    [ArtistId] GUID NOT NULL ON CONFLICT ABORT REFERENCES Artist([Id]) ON DELETE CASCADE ON UPDATE NO ACTION, 
    [TrackId] GUID NOT NULL ON CONFLICT ABORT REFERENCES Track([Id]) ON DELETE CASCADE ON UPDATE NO ACTION, 
    UNIQUE([ArtistId] ASC, [TrackId] ASC) ON CONFLICT ABORT);

CREATE TABLE IF NOT EXISTS [CoverArt](
    [TrackId] GUID NOT NULL ON CONFLICT ABORT REFERENCES Track([Id]) ON DELETE CASCADE ON UPDATE NO ACTION, 
    [CoverArtTypeId] INT NOT NULL ON CONFLICT ABORT REFERENCES CoverArtType([Id]) ON DELETE CASCADE ON UPDATE NO ACTION, 
    [MimeType] NVARCHAR NOT NULL ON CONFLICT ABORT, 
    [Size] INT NOT NULL ON CONFLICT ABORT);

CREATE TABLE IF NOT EXISTS [CoverArtType](
    [Id] INT PRIMARY KEY ASC ON CONFLICT ABORT NOT NULL ON CONFLICT ABORT UNIQUE ON CONFLICT ABORT, 
    [Name] NVARCHAR NOT NULL ON CONFLICT ABORT UNIQUE ON CONFLICT ABORT, 
    UNIQUE([Name] ASC) ON CONFLICT ABORT);

CREATE TABLE IF NOT EXISTS [Disposition](
    [Id] GUID PRIMARY KEY ASC ON CONFLICT ABORT NOT NULL ON CONFLICT ABORT UNIQUE ON CONFLICT ABORT, 
    [CollectionId] GUID NOT NULL ON CONFLICT ABORT REFERENCES Collection([Id]) ON DELETE CASCADE, 
    [MediaTypeId] INT NOT NULL ON CONFLICT ABORT REFERENCES MediaType([Id]) ON DELETE CASCADE, 
    [Favorited] DATETIME, 
    [MediaId] GUID NOT NULL ON CONFLICT ABORT, 
    [UserId] GUID NOT NULL ON CONFLICT ABORT REFERENCES User([Id]) ON DELETE CASCADE, 
    [Rating] SMALLINT, 
    UNIQUE([UserId] ASC, [MediaId] ASC) ON CONFLICT ABORT);

CREATE TABLE IF NOT EXISTS [FileInfo](
    [TrackId] GUID NOT NULL ON CONFLICT ABORT UNIQUE ON CONFLICT ABORT REFERENCES Track([Id]) ON DELETE CASCADE ON UPDATE NO ACTION, 
    [DateCreated] DATETIME NOT NULL ON CONFLICT ABORT, 
    [DateModified] DATETIME NOT NULL ON CONFLICT ABORT, 
    [Size] INT NOT NULL ON CONFLICT ABORT, 
    [Visible] BOOL NOT NULL ON CONFLICT ABORT DEFAULT 1, 
    UNIQUE([TrackId] ASC) ON CONFLICT ABORT);

CREATE TABLE IF NOT EXISTS [Genre](
    [Id] GUID PRIMARY KEY ASC ON CONFLICT ABORT NOT NULL ON CONFLICT ABORT UNIQUE ON CONFLICT ABORT, 
    [Name] NVARCHAR NOT NULL ON CONFLICT ABORT, 
    [CollectionId] GUID NOT NULL ON CONFLICT ABORT REFERENCES Collection([Id]) ON DELETE CASCADE ON UPDATE NO ACTION, 
    UNIQUE([CollectionId] ASC, [Name] ASC) ON CONFLICT ABORT);

CREATE TABLE IF NOT EXISTS [GenreToArtist](
    [GenreId] GUID NOT NULL ON CONFLICT ABORT REFERENCES Genre([Id]) ON DELETE CASCADE ON UPDATE NO ACTION, 
    [ArtistId] GUID NOT NULL ON CONFLICT ABORT REFERENCES Artist([Id]) ON DELETE CASCADE ON UPDATE NO ACTION, 
    UNIQUE([GenreId] COLLATE [BINARY], [ArtistId] COLLATE [BINARY]) ON CONFLICT ABORT);

CREATE TABLE IF NOT EXISTS [GenreToTrack](
    [GenreId] GUID NOT NULL ON CONFLICT ABORT REFERENCES Genre([Id]) ON DELETE CASCADE ON UPDATE NO ACTION, 
    [TrackId] GUID NOT NULL ON CONFLICT ABORT REFERENCES Track([Id]) ON DELETE CASCADE ON UPDATE NO ACTION, 
    UNIQUE([GenreId] COLLATE [BINARY], [TrackId] COLLATE [BINARY]) ON CONFLICT ABORT);

CREATE TABLE IF NOT EXISTS [Hash](
    [TrackId] GUID NOT NULL ON CONFLICT ABORT UNIQUE ON CONFLICT ABORT REFERENCES Track([Id]) ON DELETE CASCADE ON UPDATE NO ACTION, 
    [HashTypeId] INT NOT NULL ON CONFLICT ABORT REFERENCES HashType([Id]) ON DELETE CASCADE ON UPDATE NO ACTION, 
    [Hash] NVARCHAR NOT NULL ON CONFLICT ABORT, 
    UNIQUE([TrackId] ASC, [HashTypeId] ASC) ON CONFLICT ABORT);

CREATE TABLE IF NOT EXISTS [HashType](
    [Id] INT PRIMARY KEY ASC NOT NULL ON CONFLICT ABORT UNIQUE ON CONFLICT ABORT, 
    [Name] NVARCHAR NOT NULL ON CONFLICT ABORT UNIQUE ON CONFLICT ABORT, 
    UNIQUE([Name] ASC) ON CONFLICT ABORT);

CREATE TABLE IF NOT EXISTS [History](
    [Id] GUID NOT NULL ON CONFLICT ABORT, 
    [Timestamp] DATETIME NOT NULL ON CONFLICT ABORT, 
    [HistoryTypeId] INT NOT NULL ON CONFLICT ABORT REFERENCES HistoryType([Id]) ON DELETE CASCADE ON UPDATE NO ACTION);

CREATE TABLE IF NOT EXISTS [HistoryType](
    [Id] INT PRIMARY KEY ASC ON CONFLICT ABORT NOT NULL ON CONFLICT ABORT UNIQUE ON CONFLICT ABORT, 
    [Name] NVARCHAR NOT NULL ON CONFLICT ABORT UNIQUE ON CONFLICT ABORT, 
    UNIQUE([Name] ASC) ON CONFLICT ABORT);

CREATE TABLE IF NOT EXISTS [LastFm](
    [Id] GUID PRIMARY KEY ASC ON CONFLICT ABORT NOT NULL ON CONFLICT ABORT UNIQUE ON CONFLICT ABORT COLLATE BINARY, 
    [LastFmId] NVARCHAR, 
    [MusicBrainzId] NVARCHAR UNIQUE ON CONFLICT ABORT, 
    [Url] NVARCHAR, 
    [Details] NVARCHAR, 
    [SmallImageUrl] NVARCHAR, 
    [MediumImageUrl] NVARCHAR, 
    [LargeImageUrl] NVARCHAR, 
    [LargestImageUrl] NVARCHAR);

CREATE TABLE IF NOT EXISTS [Marker](
    [TrackId] GUID NOT NULL ON CONFLICT ABORT REFERENCES Track([Id]) ON DELETE CASCADE, 
    [UserId] GUID NOT NULL ON CONFLICT ABORT REFERENCES User([Id]) ON DELETE CASCADE, 
    [Position] INT NOT NULL ON CONFLICT ABORT, 
    [Comment] NVARCHAR, 
    UNIQUE([TrackId], [UserId]) ON CONFLICT ABORT);

CREATE TABLE IF NOT EXISTS [MediaInfo](
    [Id] GUID PRIMARY KEY ASC ON CONFLICT ABORT NOT NULL ON CONFLICT ABORT UNIQUE ON CONFLICT ABORT, 
    [MediaId] GUID NOT NULL ON CONFLICT ABORT UNIQUE ON CONFLICT ABORT, 
    [MusicBrainzId] NVARCHAR, 
    [LastFmId] NVARCHAR, 
    UNIQUE([MediaId] COLLATE [BINARY]) ON CONFLICT ABORT);

CREATE TABLE IF NOT EXISTS [MediaType](
    [Id] INT PRIMARY KEY ASC ON CONFLICT ABORT NOT NULL ON CONFLICT ABORT UNIQUE ON CONFLICT ABORT, 
    [Name] NVARCHAR NOT NULL ON CONFLICT ABORT UNIQUE ON CONFLICT ABORT, 
    UNIQUE([Name]) ON CONFLICT ABORT);

CREATE TABLE IF NOT EXISTS [Playback](
    [Address] NVARCHAR, 
    [ClientId] NVARCHAR, 
    [TrackId] GUID NOT NULL ON CONFLICT ABORT REFERENCES Track([Id]) ON DELETE CASCADE ON UPDATE NO ACTION, 
    [Timestamp] DATETIME NOT NULL ON CONFLICT ABORT, 
    [UserId] GUID NOT NULL ON CONFLICT ABORT REFERENCES User([Id]) ON DELETE CASCADE ON UPDATE NO ACTION);

CREATE TABLE IF NOT EXISTS [Playlist](
    [Id] GUID PRIMARY KEY ASC ON CONFLICT ABORT NOT NULL ON CONFLICT ABORT UNIQUE ON CONFLICT ABORT, 
    [UserId] GUID NOT NULL ON CONFLICT ABORT REFERENCES User([Id]) ON DELETE CASCADE ON UPDATE NO ACTION, 
    [Name] NVARCHAR NOT NULL ON CONFLICT ABORT, 
    [Comment] NVARCHAR, 
    [Accessibility] INT NOT NULL ON CONFLICT ABORT, 
    UNIQUE([UserId], [Name]) ON CONFLICT ABORT);

CREATE TABLE IF NOT EXISTS [PlayQueue](
    [Id] GUID PRIMARY KEY ASC ON CONFLICT ABORT NOT NULL ON CONFLICT ABORT UNIQUE ON CONFLICT ABORT, 
    [UserId] GUID NOT NULL ON CONFLICT ABORT UNIQUE ON CONFLICT ABORT REFERENCES User([Id]) ON DELETE CASCADE ON UPDATE NO ACTION, 
    [ClientName] NVARCHAR NOT NULL ON CONFLICT ABORT, 
    [CurrentTrackId] GUID REFERENCES Track([Id]) ON DELETE SET NULL ON UPDATE NO ACTION, 
    [Position] INT, 
    UNIQUE([UserId] ASC) ON CONFLICT ABORT);

CREATE TABLE IF NOT EXISTS [ProducerToTrack](
    [ArtistId] GUID NOT NULL ON CONFLICT ABORT REFERENCES Artist([Id]) ON DELETE CASCADE ON UPDATE NO ACTION, 
    [TrackId] GUID NOT NULL ON CONFLICT ABORT REFERENCES Track([Id]) ON DELETE CASCADE ON UPDATE NO ACTION, 
    UNIQUE([TrackId] COLLATE [BINARY], [ArtistId] COLLATE [BINARY]) ON CONFLICT ABORT);

CREATE TABLE IF NOT EXISTS [RadioStation](
    [Id] GUID PRIMARY KEY ASC ON CONFLICT ABORT NOT NULL ON CONFLICT ABORT UNIQUE ON CONFLICT ABORT, 
    [Name] NVARCHAR NOT NULL ON CONFLICT ABORT, 
    [StreamUrl] NVARCHAR NOT NULL ON CONFLICT ABORT, 
    [HomepageUrl] NVARCHAR);

CREATE TABLE IF NOT EXISTS [ReplayGain](
    [TrackId] GUID NOT NULL ON CONFLICT ABORT UNIQUE ON CONFLICT ABORT REFERENCES Track([Id]) ON DELETE CASCADE ON UPDATE NO ACTION, 
    [AlbumGain] DOUBLE, 
    [AlbumPeak] DOUBLE, 
    [TrackGain] DOUBLE, 
    [TrackPeak] DOUBLE, 
    UNIQUE([TrackId] ASC) ON CONFLICT ABORT);

CREATE TABLE IF NOT EXISTS [Role](
    [Id] INT PRIMARY KEY ASC ON CONFLICT ABORT NOT NULL ON CONFLICT ABORT UNIQUE ON CONFLICT ABORT, 
    [Name] NVARCHAR NOT NULL ON CONFLICT ABORT UNIQUE ON CONFLICT ABORT, 
    UNIQUE([Name] ASC) ON CONFLICT ABORT);

CREATE TABLE IF NOT EXISTS [Schema](
    [Version] INT NOT NULL ON CONFLICT ABORT);

CREATE TABLE IF NOT EXISTS [Status](
    [Id] GUID PRIMARY KEY ASC ON CONFLICT ABORT NOT NULL ON CONFLICT ABORT UNIQUE ON CONFLICT ABORT, 
    [Enabled] BOOLEAN NOT NULL ON CONFLICT ABORT DEFAULT 1, 
    UNIQUE([Id]) ON CONFLICT ABORT);

CREATE TABLE IF NOT EXISTS [Style](
    [Id] GUID PRIMARY KEY ASC ON CONFLICT ABORT NOT NULL ON CONFLICT ABORT UNIQUE ON CONFLICT ABORT, 
    [CollectionId] GUID NOT NULL ON CONFLICT ABORT REFERENCES Collection([Id]) ON DELETE CASCADE ON UPDATE NO ACTION, 
    [Name] NVARCHAR NOT NULL ON CONFLICT ABORT, 
    UNIQUE([CollectionId] ASC, [Name] ASC) ON CONFLICT ABORT);

CREATE TABLE IF NOT EXISTS [StyleToArtist](
    [StyleId] GUID NOT NULL ON CONFLICT ABORT REFERENCES Style([Id]) ON DELETE CASCADE ON UPDATE NO ACTION, 
    [ArtistId] GUID NOT NULL ON CONFLICT ABORT REFERENCES Artist([Id]) ON DELETE CASCADE ON UPDATE NO ACTION, 
    UNIQUE([StyleId] ASC, [ArtistId] ASC) ON CONFLICT ABORT);

CREATE TABLE IF NOT EXISTS [StyleToTrack](
    [StyleId] GUID NOT NULL ON CONFLICT ABORT REFERENCES Style([Id]) ON DELETE CASCADE ON UPDATE NO ACTION, 
    [TrackId] GUID NOT NULL ON CONFLICT ABORT REFERENCES Track([Id]) ON DELETE CASCADE ON UPDATE NO ACTION, 
    UNIQUE([StyleId] ASC, [TrackId] ASC) ON CONFLICT ABORT);

CREATE TABLE IF NOT EXISTS [Track](
    [Id] GUID PRIMARY KEY ASC ON CONFLICT ABORT NOT NULL ON CONFLICT ABORT UNIQUE ON CONFLICT ABORT, 
    [Name] NVARCHAR, 
    [Comment] NVARCHAR, 
    [Disc] INT, 
    [Number] INT, 
    [ReleaseDate] INT, 
    [Duration] INT NOT NULL ON CONFLICT ABORT, 
    [Bitrate] INT NOT NULL, 
    [Channels] INT NOT NULL ON CONFLICT ABORT, 
    [SampleRate] INT NOT NULL ON CONFLICT ABORT, 
    [ContentType] NVARCHAR, 
    [Path] NVARCHAR NOT NULL, 
    [CollectionId] GUID NOT NULL ON CONFLICT ABORT REFERENCES Collection([Id]) ON DELETE CASCADE ON UPDATE NO ACTION, 
    UNIQUE([CollectionId] ASC, [Path] ASC) ON CONFLICT ABORT);

CREATE TABLE IF NOT EXISTS [TrackToAlbum](
    [TrackId] GUID NOT NULL ON CONFLICT ABORT REFERENCES Track([Id]) ON DELETE CASCADE ON UPDATE NO ACTION, 
    [AlbumId] GUID NOT NULL ON CONFLICT ABORT REFERENCES Album([Id]) ON DELETE CASCADE ON UPDATE NO ACTION, 
    UNIQUE([TrackId] ASC, [AlbumId] ASC) ON CONFLICT ABORT);

CREATE TABLE IF NOT EXISTS [TrackToPlaylist](
    [PlaylistId] GUID NOT NULL ON CONFLICT ABORT REFERENCES Playlist([Id]) ON DELETE CASCADE ON UPDATE NO ACTION, 
    [TrackId] GUID NOT NULL ON CONFLICT ABORT REFERENCES Track([Id]) ON DELETE CASCADE ON UPDATE NO ACTION, 
    [Position] INT NOT NULL ON CONFLICT ABORT, 
    UNIQUE([PlaylistId] ASC, [TrackId] ASC, [Position] ASC) ON CONFLICT ABORT);

CREATE TABLE IF NOT EXISTS [TrackToPlayQueue](
    [PlayQueueId] GUID NOT NULL ON CONFLICT ABORT COLLATE BINARY REFERENCES PlayQueue([Id]) ON DELETE CASCADE ON UPDATE NO ACTION, 
    [TrackId] GUID NOT NULL ON CONFLICT ABORT COLLATE BINARY REFERENCES Track([Id]) ON DELETE CASCADE ON UPDATE NO ACTION, 
    [Position] INT NOT NULL ON CONFLICT ABORT, 
    UNIQUE([PlayQueueId] ASC, [Position] ASC) ON CONFLICT ABORT);

CREATE TABLE IF NOT EXISTS [User](
    [Id] GUID PRIMARY KEY ASC NOT NULL ON CONFLICT ABORT UNIQUE ON CONFLICT ABORT COLLATE BINARY, 
    [Name] NVARCHAR NOT NULL ON CONFLICT ABORT UNIQUE ON CONFLICT ABORT COLLATE NOCASE, 
    [EmailAddress] NVARCHAR, 
    [Password] NVARCHAR NOT NULL ON CONFLICT ABORT, 
    UNIQUE([Name] ASC) ON CONFLICT ABORT);

CREATE TABLE IF NOT EXISTS [UserToCollection](
    [UserId] GUID NOT NULL ON CONFLICT ABORT COLLATE BINARY REFERENCES User([Id]) ON DELETE CASCADE, 
    [CollectionId] GUID NOT NULL ON CONFLICT ABORT COLLATE BINARY REFERENCES Collection([Id]) ON DELETE CASCADE, 
    UNIQUE([UserId] ASC, [CollectionId] ASC) ON CONFLICT ABORT);

CREATE TABLE IF NOT EXISTS [UserToRole](
    [UserId] GUID NOT NULL ON CONFLICT ABORT COLLATE BINARY REFERENCES User([Id]) ON DELETE CASCADE, 
    [RoleId] INT NOT NULL ON CONFLICT ABORT REFERENCES Role([Id]) ON DELETE CASCADE, 
    UNIQUE([UserId] ASC, [RoleId] ASC) ON CONFLICT ABORT);

CREATE INDEX IF NOT EXISTS [Album_ArtistIds]
ON [Album](
    [ArtistIds] ASC);

CREATE INDEX IF NOT EXISTS [Album_CollectionId]
ON [Album](
    [CollectionId] COLLATE [BINARY]);

CREATE INDEX IF NOT EXISTS [Album_Name]
ON [Album](
    [Name] ASC);

CREATE INDEX IF NOT EXISTS [ArtistToAlbum_AlbumId]
ON [ArtistToAlbum](
    [AlbumId]);

CREATE INDEX IF NOT EXISTS [ArtistToAlbum_ArtistId]
ON [ArtistToAlbum](
    [ArtistId] ASC);

CREATE INDEX IF NOT EXISTS [ArtistToTrack_ArtistId]
ON [ArtistToTrack](
    [ArtistId] ASC);

CREATE INDEX IF NOT EXISTS [ArtistToTrack_TrackId]
ON [ArtistToTrack](
    [TrackId] ASC);

CREATE INDEX IF NOT EXISTS [Artist_CollectionId]
ON [Artist](
    [CollectionId] ASC);

CREATE INDEX IF NOT EXISTS [Artist_Name]
ON [Artist](
    [Name] ASC);

CREATE INDEX IF NOT EXISTS [Chat_Timestamp]
ON [Chat](
    [Timestamp] ASC);

CREATE INDEX IF NOT EXISTS [Chat_UserId]
ON [Chat](
    [UserId] ASC);

CREATE INDEX IF NOT EXISTS [ComposerToTrack_ArtistId]
ON [ComposerToTrack](
    [ArtistId] ASC);

CREATE INDEX IF NOT EXISTS [ComposerToTrack_TrackId]
ON [ComposerToTrack](
    [TrackId] ASC);

CREATE INDEX IF NOT EXISTS [CoverArt_CoverArtTypeId]
ON [CoverArt](
    [CoverArtTypeId] ASC);

CREATE INDEX IF NOT EXISTS [CoverArt_TrackId]
ON [CoverArt](
    [TrackId] ASC);

CREATE INDEX IF NOT EXISTS [Disposition_MediaId]
ON [Disposition](
    [MediaId] ASC);

CREATE INDEX IF NOT EXISTS [Disposition_UserId]
ON [Disposition](
    [UserId] ASC);

CREATE INDEX IF NOT EXISTS [GenreToArtist_ArtistId]
ON [GenreToArtist](
    [ArtistId] ASC);

CREATE INDEX IF NOT EXISTS [GenreToArtist_GenreId]
ON [GenreToArtist](
    [GenreId] ASC);

CREATE INDEX IF NOT EXISTS [GenreToTrack_GenreId]
ON [GenreToTrack](
    [GenreId] ASC);

CREATE INDEX IF NOT EXISTS [GenreToTrack_TrackId]
ON [GenreToTrack](
    [TrackId] ASC);

CREATE INDEX IF NOT EXISTS [Genre_CollectionId]
ON [Genre](
    [CollectionId] ASC);

CREATE INDEX IF NOT EXISTS [Genre_Name]
ON [Genre](
    [Name] ASC);

CREATE INDEX IF NOT EXISTS [History_HistoryTypeId]
ON [History](
    [HistoryTypeId] ASC);

CREATE INDEX IF NOT EXISTS [History_Id]
ON [History](
    [Id] ASC);

CREATE INDEX IF NOT EXISTS [LastFm_MusicBrainzId]
ON [LastFm](
    [MusicBrainzId] ASC);

CREATE INDEX IF NOT EXISTS [MediaInfo_LastFmId]
ON [MediaInfo](
    [LastFmId] ASC);

CREATE INDEX IF NOT EXISTS [MediaInfo_MusicBrainzId]
ON [MediaInfo](
    [MusicBrainzId] ASC);

CREATE INDEX IF NOT EXISTS [Playback_TrackId]
ON [Playback](
    [TrackId] ASC);

CREATE INDEX IF NOT EXISTS [Playback_UserId]
ON [Playback](
    [UserId] ASC);

CREATE INDEX IF NOT EXISTS [Playlist_Accessibility]
ON [Playlist](
    [Accessibility] ASC);

CREATE INDEX IF NOT EXISTS [Playlist_Name]
ON [Playlist](
    [Name] ASC);

CREATE INDEX IF NOT EXISTS [Playlist_UserId]
ON [Playlist](
    [UserId] ASC);

CREATE INDEX IF NOT EXISTS [ProducerToTrack_ArtistId]
ON [ProducerToTrack](
    [ArtistId] ASC);

CREATE INDEX IF NOT EXISTS [ProducerToTrack_TrackId]
ON [ProducerToTrack](
    [TrackId] ASC);

CREATE INDEX IF NOT EXISTS [StyleToArtist_ArtistId]
ON [StyleToArtist](
    [ArtistId] ASC);

CREATE INDEX IF NOT EXISTS [StyleToArtist_StyleId]
ON [StyleToArtist](
    [StyleId] ASC);

CREATE INDEX IF NOT EXISTS [StyleToTrack_StyleId]
ON [StyleToTrack](
    [StyleId] ASC);

CREATE INDEX IF NOT EXISTS [StyleToTrack_TrackId]
ON [StyleToTrack](
    [TrackId] ASC);

CREATE INDEX IF NOT EXISTS [Style_CollectionId]
ON [Style](
    [CollectionId] COLLATE [BINARY]);

CREATE INDEX IF NOT EXISTS [Style_Name]
ON [Style](
    [Name] ASC);

CREATE INDEX IF NOT EXISTS [TrackToAlbum_AlbumId]
ON [TrackToAlbum](
    [AlbumId] ASC);

CREATE INDEX IF NOT EXISTS [TrackToAlbum_TrackId]
ON [TrackToAlbum](
    [TrackId] ASC);

CREATE INDEX IF NOT EXISTS [TrackToPlaylist_TrackId_PlaylistId]
ON [TrackToPlaylist](
    [TrackId] ASC, 
    [PlaylistId] ASC);

CREATE INDEX IF NOT EXISTS [TrackToPlayQueue_PlayQueueId]
ON [TrackToPlayQueue](
    [PlayQueueId] COLLATE [BINARY]);

CREATE INDEX IF NOT EXISTS [Track_Name]
ON [Track](
    [Name] COLLATE [NOCASE] ASC);

CREATE INDEX IF NOT EXISTS [Track_ReleaseDate]
ON [Track](
    [ReleaseDate] ASC);

CREATE INDEX IF NOT EXISTS [UserToCollection_CollectionId]
ON [UserToCollection](
    [CollectionId] COLLATE [BINARY]);

CREATE INDEX IF NOT EXISTS [UserToCollection_UserId]
ON [UserToCollection](
    [UserId] COLLATE [BINARY]);

CREATE INDEX IF NOT EXISTS [UserToRole_RoleId]
ON [UserToRole](
    [RoleId] ASC);

CREATE INDEX IF NOT EXISTS [UserToRole_UserId]
ON [UserToRole](
    [UserId] COLLATE [BINARY]);

CREATE TRIGGER IF NOT EXISTS [Album_History_Insert] AFTER INSERT ON [Album]
BEGIN
    INSERT INTO [History]
        ([Id], 
        [Timestamp], 
        [HistoryTypeId])
        VALUES ([New].[Id], STRFTIME ('%Y-%m-%dT%H:%M:%fZ', 'now'), 0);
END;

CREATE TRIGGER IF NOT EXISTS [Album_History_Update] AFTER UPDATE ON [Album]
BEGIN
    INSERT INTO [History]
        ([Id], 
        [Timestamp], 
        [HistoryTypeId])
        VALUES ([New].[Id], STRFTIME ('%Y-%m-%dT%H:%M:%fZ', 'now'), 1);
END;

CREATE TRIGGER IF NOT EXISTS [Artist_History_Insert] AFTER INSERT ON [Artist]
BEGIN
    INSERT INTO [History]
        ([Id], 
        [Timestamp], 
        [HistoryTypeId])
        VALUES ([New].[Id], STRFTIME ('%Y-%m-%dT%H:%M:%fZ', 'now'), 0);
END;

CREATE TRIGGER IF NOT EXISTS [Artist_History_Update] AFTER UPDATE ON [Artist]
BEGIN
    INSERT INTO [History]
        ([Id], 
        [Timestamp], 
        [HistoryTypeId])
        VALUES ([New].[Id], STRFTIME ('%Y-%m-%dT%H:%M:%fZ', 'now'), 1);
END;

CREATE TRIGGER IF NOT EXISTS [Collection_History_Insert] AFTER INSERT ON [Collection]
BEGIN
    INSERT INTO [History]
        ([Id], 
        [Timestamp], 
        [HistoryTypeId])
        VALUES ([New].[Id], STRFTIME ('%Y-%m-%dT%H:%M:%fZ', 'now'), 0);
END;

CREATE TRIGGER IF NOT EXISTS [Collection_History_Update] AFTER UPDATE ON [Collection]
BEGIN
    INSERT INTO [History]
        ([Id], 
        [Timestamp], 
        [HistoryTypeId])
        VALUES ([New].[Id], STRFTIME ('%Y-%m-%dT%H:%M:%fZ', 'now'), 1);
END;

CREATE TRIGGER IF NOT EXISTS [Genre_History_Insert] AFTER INSERT ON [Genre]
BEGIN
    INSERT INTO [History]
        ([Id], 
        [Timestamp], 
        [HistoryTypeId])
        VALUES ([New].[Id], STRFTIME ('%Y-%m-%dT%H:%M:%fZ', 'now'), 0);
END;

CREATE TRIGGER IF NOT EXISTS [Genre_History_Update] AFTER UPDATE ON [Genre]
BEGIN
    INSERT INTO [History]
        ([Id], 
        [Timestamp], 
        [HistoryTypeId])
        VALUES ([New].[Id], STRFTIME ('%Y-%m-%dT%H:%M:%fZ', 'now'), 1);
END;

CREATE TRIGGER IF NOT EXISTS [LastFm_History_Insert] AFTER INSERT ON [LastFm]
BEGIN
    INSERT INTO [History]
        ([Id], 
        [Timestamp], 
        [HistoryTypeId])
        VALUES ([New].[Id], STRFTIME ('%Y-%m-%dT%H:%M:%fZ', 'now'), 0);
END;

CREATE TRIGGER IF NOT EXISTS [LastFm_History_Update] AFTER UPDATE ON [LastFm]
BEGIN
    INSERT INTO [History]
        ([Id], 
        [Timestamp], 
        [HistoryTypeId])
        VALUES ([New].[Id], STRFTIME ('%Y-%m-%dT%H:%M:%fZ', 'now'), 1);
END;

CREATE TRIGGER IF NOT EXISTS [MediaInfo_History_Insert] AFTER INSERT ON [MediaInfo]
BEGIN
    INSERT INTO [History]
        ([Id], 
        [Timestamp], 
        [HistoryTypeId])
        VALUES ([New].[Id], STRFTIME ('%Y-%m-%dT%H:%M:%fZ', 'now'), 0);
END;

CREATE TRIGGER IF NOT EXISTS [MediaInfo_History_Update] AFTER UPDATE ON [MediaInfo]
BEGIN
    INSERT INTO [History]
        ([Id], 
        [Timestamp], 
        [HistoryTypeId])
        VALUES ([New].[Id], STRFTIME ('%Y-%m-%dT%H:%M:%fZ', 'now'), 1);
END;

CREATE TRIGGER IF NOT EXISTS [Playlist_History_Insert] AFTER INSERT ON [Playlist]
BEGIN
    INSERT INTO [History]
        ([Id], 
        [Timestamp], 
        [HistoryTypeId])
        VALUES ([New].[Id], STRFTIME ('%Y-%m-%dT%H:%M:%fZ', 'now'), 0);
END;

CREATE TRIGGER IF NOT EXISTS [Playlist_History_Update] AFTER UPDATE ON [Playlist]
BEGIN
    INSERT INTO [History]
        ([Id], 
        [Timestamp], 
        [HistoryTypeId])
        VALUES ([New].[Id], STRFTIME ('%Y-%m-%dT%H:%M:%fZ', 'now'), 1);
END;

CREATE TRIGGER IF NOT EXISTS [PlayQueue_History_Insert] AFTER INSERT ON [PlayQueue]
BEGIN
    INSERT INTO [History]
        ([Id], 
        [Timestamp], 
        [HistoryTypeId])
        VALUES ([New].[Id], STRFTIME ('%Y-%m-%dT%H:%M:%fZ', 'now'), 0);
END;

CREATE TRIGGER IF NOT EXISTS [PlayQueue_History_Update] AFTER UPDATE ON [PlayQueue]
BEGIN
    INSERT INTO [History]
        ([Id], 
        [Timestamp], 
        [HistoryTypeId])
        VALUES ([New].[Id], STRFTIME ('%Y-%m-%dT%H:%M:%fZ', 'now'), 1);
END;

CREATE TRIGGER IF NOT EXISTS [Style_History_Insert] AFTER INSERT ON [Style]
BEGIN
    INSERT INTO [History]
        ([Id], 
        [Timestamp], 
        [HistoryTypeId])
        VALUES ([New].[Id], STRFTIME ('%Y-%m-%dT%H:%M:%fZ', 'now'), 0);
END;

CREATE TRIGGER IF NOT EXISTS [Style_History_Update] AFTER UPDATE ON [Style]
BEGIN
    INSERT INTO [History]
        ([Id], 
        [Timestamp], 
        [HistoryTypeId])
        VALUES ([New].[Id], STRFTIME ('%Y-%m-%dT%H:%M:%fZ', 'now'), 1);
END;

CREATE TRIGGER IF NOT EXISTS [Track_History_Insert] AFTER INSERT ON [Track]
BEGIN
    INSERT INTO [History]
        ([Id], 
        [Timestamp], 
        [HistoryTypeId])
        VALUES ([New].[Id], STRFTIME ('%Y-%m-%dT%H:%M:%fZ', 'now'), 0);
END;

CREATE TRIGGER IF NOT EXISTS [Track_History_Update] AFTER UPDATE ON [Track]
BEGIN
    INSERT INTO [History]
        ([Id], 
        [Timestamp], 
        [HistoryTypeId])
        VALUES ([New].[Id], STRFTIME ('%Y-%m-%dT%H:%M:%fZ', 'now'), 1);
END;

CREATE TRIGGER IF NOT EXISTS [User_History_Insert] AFTER INSERT ON [User]
BEGIN
    INSERT INTO [History]
        ([Id], 
        [Timestamp], 
        [HistoryTypeId])
        VALUES ([New].[Id], STRFTIME ('%Y-%m-%dT%H:%M:%fZ', 'now'), 0);
END;

CREATE TRIGGER IF NOT EXISTS [User_History_Update] AFTER UPDATE ON [User]
BEGIN
    INSERT INTO [History]
        ([Id], 
        [Timestamp], 
        [HistoryTypeId])
        VALUES ([New].[Id], STRFTIME ('%Y-%m-%dT%H:%M:%fZ', 'now'), 1);
END;

CREATE TRIGGER IF NOT EXISTS [RadioStation_History_Update] AFTER UPDATE ON [RadioStation]
BEGIN
    INSERT INTO [History]
        ([Id], 
        [Timestamp], 
        [HistoryTypeId])
        VALUES ([New].[Id], STRFTIME ('%Y-%m-%dT%H:%M:%fZ', 'now'), 1);
END;

CREATE TRIGGER IF NOT EXISTS [RadioStation_History_Insert] AFTER INSERT ON [RadioStation]
BEGIN
    INSERT INTO [History]
        ([Id], 
        [Timestamp], 
        [HistoryTypeId])
        VALUES ([New].[Id], STRFTIME ('%Y-%m-%dT%H:%M:%fZ', 'now'), 0);
END;


